import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import path from 'path';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// 获取输出目录参数
let outDir = './dist';
for (let i = 0; i < process.argv.length; i++) {
    const arg = process.argv[i];
    // 支持两种格式: --outdir=./dist 或 --outdir ./dist
    if (arg.startsWith('--outdir=')) {
        outDir = arg.split('=')[1];
    } else if (arg === '--outdir' && i + 1 < process.argv.length) {
        outDir = process.argv[i + 1];
    }
}

// 确保输出目录存在
if (outDir !== './') {
    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }
}

// CSS 插件：将 CSS 转换为 JavaScript 字符串并注入到 DOM
const cssPlugin = {
    name: 'css',
    setup(build) {
        build.onLoad({ filter: /\.css$/ }, async (args) => {
            const css = await fs.promises.readFile(args.path, 'utf8');
            
            // 将 CSS 内容转换为可以注入 DOM 的 JavaScript 代码
            const contents = `
                (function() {
                    if (typeof document !== 'undefined') {
                        const style = document.createElement('style');
                        style.textContent = ${JSON.stringify(css)};
                        document.head.appendChild(style);
                    }
                })();
            `;
            
            return {
                contents,
                loader: 'js',
            };
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins
    ],
    format: 'cjs',
    target: 'es2020', // 升级到ES2020以支持BigInt字面量
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: path.join(outDir, 'main.js'),
    plugins: [cssPlugin], // 添加 CSS 插件
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
